name: Maven Build

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Test with Maven
        run: mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/
          
      - name: Build with Maven
        run: mvn clean package
      - name: Build Docker image
        run: docker build -t ${{ github.event.repository.name }}:latest .
