name: Vue Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
          
      
        
